using System;
using System.Text;

public partial class SexSpider_GetListData3 : System.Web.UI.Page
{
    protected void Page_Load(object sender, EventArgs e)
    {
        StringBuilder result = new StringBuilder();

		//start
        result.Append("{\"site_list\":[");
        //1. 好了KK
        result.Append("{\"siteid\":\"1\",\"siterank\":\"A01\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"好了KK【快速】\",\"listpage\":\"1-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"https://se.haoav23.com\",\"sitelink\":\"https://se.haoav23.com/listhtml/1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"title\\\">\",\"imageend\":\"<divclass=\\\"pagea\\\">\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //26. 激情五月
        result.Append("{\"siteid\":\"26\",\"siterank\":\"A02\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"激情五月\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.65zzzz.com\",\"sitelink\":\"http://www.65zzzz.com/p01/index.html\",\"liststart\":\"<divclass=\\\"typelist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"view1\\\"class=\\\"mtop\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/htm\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //3. 摸逼逼
        result.Append("{\"siteid\":\"3\",\"siterank\":\"A03\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"摸逼逼\",\"listpage\":\"(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mbbb33.com\",\"sitelink\":\"http://www.mbbb33.com/mnv67/6/1.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=n_bd>\",\"imageend\":\"</div>\",\"oninclude\":\"/admrw\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //4. 哥哥嘿
        result.Append("{\"siteid\":\"4\",\"siterank\":\"A04\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"哥哥嘿【失效】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.ddfuli.com\",\"sitelink\":\"http://www.ddfuli.com/tupian/toupai/index.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=temp23>\",\"imageend\":\"</div>\",\"oninclude\":\"/tupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //5. AV天堂网
        result.Append("{\"siteid\":\"5\",\"siterank\":\"A05\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"AV天堂网【失效】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.avvav2016.com\",\"sitelink\":\"http://www.avvav2016.com/zipaitoupai/index.html\",\"liststart\":\"<divclass=\\\"newslist\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"imagestart\":\"<divid=\\\"text_novel\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/zipaitoupai\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //24. 夜夜嘿
        result.Append("{\"siteid\":\"24\",\"siterank\":\"A06\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"夜夜嘿【翻墙】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://yeyehei.cc\",\"sitelink\":\"http://yeyehei.cc/pic/zipai/index.html\",\"liststart\":\"<divclass=\\\"idxnew\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/pic/zipai\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //9. 爱色阁-自拍专区
        result.Append("{\"siteid\":\"9\",\"siterank\":\"A07\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"爱色阁-自拍偷拍【失效】\",\"listpage\":\"index20_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.964vv.com\",\"sitelink\":\"http://www.964vv.com/html/part/index20.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //27. 爱色阁-性爱自拍
        result.Append("{\"siteid\":\"27\",\"siterank\":\"A08\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"爱色阁-性爱自拍【失效】\",\"listpage\":\"index43_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.964vv.com\",\"sitelink\":\"http://www.964vv.com/html/part/index43.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //7. 91Porn-原创申请
        result.Append("{\"siteid\":\"7\",\"siterank\":\"A09\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"91Porn-原创申请\",\"listpage\":\"forumdisplay.php?fid=19&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://91.t9j.space/\",\"sitelink\":\"http://91.t9j.space/forumdisplay.php?fid=19&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //12. 91Porn-我爱我妻
        result.Append("{\"siteid\":\"12\",\"siterank\":\"A10\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"91Porn-我爱我妻\",\"listpage\":\"forumdisplay.php?fid=21&orderby=dateline&page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://91.t9j.space/\",\"sitelink\":\"http://91.t9j.space/forumdisplay.php?fid=21&orderby=dateline&page=1\",\"liststart\":\"<divid=\\\"threadlist\\\"\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"threadtitle\\\">\",\"imageend\":\"<divclass=\\\"postactions\\\">\",\"oninclude\":\"viewthread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //8. 超碰在线视频
        result.Append("{\"siteid\":\"8\",\"siterank\":\"A11\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"超碰在线视频\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://gan.tv.t88.space\",\"sitelink\":\"http://gan.tv.t88.space/albums?page=1\",\"liststart\":\"<divclass=\\\"blinkp\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<divid=\\\"album\",\"imageend\":\"<divclass=\\\"pagination\\\">\",\"oninclude\":\"/album\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagination\\\">\",\"pageend\"=\"</div>\",\"pagenext\"=\"//?page=(*)\"},");
        //22. 淫色淫色
        result.Append("{\"siteid\":\"22\",\"siterank\":\"A12\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"淫色淫色\",\"listpage\":\"index-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.myppp36.com\",\"sitelink\":\"http://www.myppp36.com/AAtupian/AAtb/zipai/index.html\",\"liststart\":\"<divclass=\\\"boxlistchannel\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"post-bd\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/AAtupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //16. 精彩生活自拍汇
        result.Append("{\"siteid\":\"16\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"精彩生活自拍汇【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.we560.com/xtu/\",\"sitelink\":\"http://bbs.we560.com/xtu\",\"liststart\":\"<divalign=center>\",\"listend\":\"</div>\",\"imagestart\":\"<table\",\"imageend\":\"</div>\",\"oninclude\":\"html/\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //17. 正妹写真套图
        result.Append("{\"siteid\":\"17\",\"siterank\":\"\",\"viplevel\":\"1\",\"ishided\":\"1\",\"sitename\":\"正妹写真套图【失效】\",\"listpage\":\"(*)\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.we560.com/xz/cn\",\"sitelink\":\"http://bbs.we560.com/xz/cn\",\"liststart\":\"<divclass=\\\"viewbox\\\">\",\"listend\":\"</body>\",\"imagestart\":\"<divclass=\\\"img-show\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //23. Ady映画网
        result.Append("{\"siteid\":\"23\",\"siterank\":\"A13\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"Ady映画网\",\"listpage\":\"New(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://jj.6ady.info\",\"sitelink\":\"http://jj.6ady.info/zjgx/New.html\",\"liststart\":\"<divclass=\\\"pre_b\\\">\",\"listend\":\"<divclass=\\\"pre_b_class_page\\\">\",\"imagestart\":\"<divclass=\\\"movie_c_pre\\\">\",\"imageend\":\"<divclass=\\\"movie_d\\\">\",\"oninclude\":\"/d\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //30. 东京干
        result.Append("{\"siteid\":\"30\",\"siterank\":\"A14\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"东京干【超快】\",\"listpage\":\"sseexx60_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.av43.xyz\",\"sitelink\":\"http://www.av43.xyz/html/part/sseexx60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //25. 久久热
        result.Append("{\"siteid\":\"25\",\"siterank\":\"A15\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"久久热\",\"listpage\":\"(*)/\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.99qq8.com\",\"sitelink\":\"http://www.99qq8.com/albums/\",\"liststart\":\"<divclass=\\\"thumbsmodels\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<divclass=\\\"models-slider-big\\\">\",\"imageend\":\"<divclass=\\\"models-slider-small\\\">\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //37. 久久热
        result.Append("{\"siteid\":\"37\",\"siterank\":\"A16\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"久久热\",\"listpage\":\"forum-169-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.99rebbs5.com/\",\"sitelink\":\"http://www.99rebbs5.com/forum-169-1.html\",\"liststart\":\"<divid=\\\"threadlist\",\"listend\":\"<divid=\\\"filter_special_menu\",\"imagestart\":\"<divclass=\\\"attach_nopermission\",\"imageend\":\"<divid=\\\"p_btn\\\"\",\"oninclude\":\"thread\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //29. 色久久
        result.Append("{\"siteid\":\"29\",\"siterank\":\"A17\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色久久\",\"listpage\":\"index27_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.110pp.com\",\"sitelink\":\"http://www.110pp.com/html/part/index27.html\",\"liststart\":\"<divid=\\\"text\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //32. 色色999
        result.Append("{\"siteid\":\"32\",\"siterank\":\"A18\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色色999【快速】\",\"listpage\":\"23-(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.6666ak.com\",\"sitelink\":\"http://www.6666ak.com/artlist/23.html\",\"liststart\":\"<divclass=\\\"atrlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divid=\\\"postmessage\\\"class=\\\"t_msgfont\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/arts\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //33. 七次郎
        result.Append("{\"siteid\":\"33\",\"siterank\":\"A19\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"七次郎【超快】\",\"listpage\":\"index_page_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.7langtu.com\",\"sitelink\":\"http://www.7langtu.com/pictures/6/index.html\",\"liststart\":\"<divclass=\\\"list-video\\\">\",\"listend\":\"<ulclass=\\\"pagination\\\">\",\"imagestart\":\"<divclass=\\\"ads_55\\\">\",\"imageend\":\"<divclass=\\\"end-list\\\">\",\"oninclude\":\"/picture\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //2. 一焦进洞
        result.Append("{\"siteid\":\"2\",\"siterank\":\"A20\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"一焦进洞【重复】\",\"listpage\":\"(*).jsp\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.yjjdo.pw\",\"sitelink\":\"http://www.yjjdo.pw/yjj2/6/1.jsp\",\"liststart\":\"<divclass=\\\"mainArea\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"picContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/yjj1\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
		//38. ♂爱AB♀
        result.Append("{\"siteid\":\"38\",\"siterank\":\"A21\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"♂爱AB♀【超快】\",\"listpage\":\"list_10_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.iab02.com\",\"sitelink\":\"http://www.iab02.com/ws/list_10_1.html\",\"liststart\":\"<divclass=main>\",\"listend\":\"<divclass=dede_pages>\",\"imagestart\":\"<divclass=\\\"article_body\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/ws\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
		//39. 撸撸嘿
        result.Append("{\"siteid\":\"39\",\"siterank\":\"A22\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"撸撸嘿【超快】\",\"listpage\":\"albums?page=(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.luluhei.tv\",\"sitelink\":\"http://www.luluhei.tv/albums?page=1\",\"liststart\":\"<divclass=\\\"container\\\">\",\"listend\":\"<divclass=\\\"list-group\\\">\",\"imagestart\":\"<divclass=\\\"col-md-8\\\">\",\"imageend\":\"<divclass=\\\"footer-container\\\">\",\"oninclude\":\"/album/\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //40. 开心五月
        result.Append("{\"siteid\":\"40\",\"siterank\":\"A23\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"开心五月-自拍偷拍\",\"listpage\":\"index9_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.ppcao99.com\",\"sitelink\":\"http://www.ppcao99.com/html/part/index9.html\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //42. 开心五月
        result.Append("{\"siteid\":\"42\",\"siterank\":\"A24\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"开心五月-综合图片\",\"listpage\":\"index16_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.ppcao99.com\",\"sitelink\":\"http://www.ppcao99.com/html/part/index16.html\",\"liststart\":\"<ulclass=\\\"textList\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"novelContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //41. 银色网
        result.Append("{\"siteid\":\"41\",\"siterank\":\"A25\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"银色网\",\"listpage\":\"19_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.84kc.com\",\"sitelink\":\"http://www.84kc.com/html/part/19.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"page\\\">\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"<liclass=\\\"last\\\">\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //28. 就去路
        result.Append("{\"siteid\":\"28\",\"siterank\":\"A26\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"就去路\",\"listpage\":\"10_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.97luwang.com\",\"sitelink\":\"http://www.97luwang.com/html/part/10.html\",\"liststart\":\"<divid=\\\"text_box\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"content\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //6. 神马影院
        result.Append("{\"siteid\":\"6\",\"siterank\":\"A27\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"神马影院\",\"listpage\":\"index60_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.av60.xyz\",\"sitelink\":\"http://www.av60.xyz/nv/you/index60.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"n_bd\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/nv/so\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //43. 插插插
        result.Append("{\"siteid\":\"43\",\"siterank\":\"A28\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"插插插【快速】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.872aa.com\",\"sitelink\":\"http://www.872aa.com/PIC01/index.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=temp23>\",\"imageend\":\"</div>\",\"oninclude\":\"/html\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //44. 奇米网
        result.Append("{\"siteid\":\"44\",\"siterank\":\"A29\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"奇米网【快速】\",\"listpage\":\"index(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.53ss.net\",\"sitelink\":\"http://www.53ss.net/it/dalutupian/index.html\",\"liststart\":\"<divclass=\\\"left\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"up\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/it/dalutupian\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //45. 色哥哥
        result.Append("{\"siteid\":\"45\",\"siterank\":\"A30\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"色哥哥\",\"listpage\":\"index32_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.sggqu.com\",\"sitelink\":\"http://www.sggqu.com/html/part/index32.html\",\"liststart\":\"<divclass=\\\"zxlist\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divclass=\\\"biaoti\\\">\",\"imageend\":\"<divclass=\\\"pagea\\\">\",\"oninclude\":\"/html/article\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //46. 66爱爱
        result.Append("{\"siteid\":\"46\",\"siterank\":\"A31\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"66爱爱\",\"listpage\":\"9_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.39pao.com\",\"sitelink\":\"http://www.39pao.com/news/other/9.html\",\"liststart\":\"<ulclass=\\\"news_list\\\">\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"news\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/news/class\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //47. 草榴社区
        result.Append("{\"siteid\":\"47\",\"siterank\":\"A32\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"草榴社区\",\"listpage\":\"thread0806.php?fid=16&search=&page=(*)\",\"pageencode\":\"gbk\",\"domain\":\"http://www.sceduu.com/\",\"sitelink\":\"http://www.sceduu.com/thread0806.php?fid=16&search=&page=1\",\"liststart\":\"id=\\\"ajaxtable\\\"\",\"listend\":\"<table\",\"imagestart\":\"<divclass=\\\"tpc_content\",\"imageend\":\"<table\",\"oninclude\":\"htm_data\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //48. 台湾妹中文网
        result.Append("{\"siteid\":\"48\",\"siterank\":\"A33\",\"viplevel\":\"1\",\"ishided\":\"0\",\"sitename\":\"台湾妹中文网\",\"listpage\":\"list5(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.373nn.com\",\"sitelink\":\"http://www.373nn.com/tupianqu/TSE/list51.html\",\"liststart\":\"<divalign=\\\"left\\\">\",\"listend\":\"</div>\",\"imagestart\":\"<divalign=\\\"left\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/tttppp\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"bpages\\\">\",\"pageend\"=\"</div>\",\"pagenext\"=\"\"},");

        ////////////////////////////////////////////////////////////////////////////VIP分隔线////////////////////////////////////////////////////////////////////////////
		
		//31. 中国人体艺术
        result.Append("{\"siteid\":\"31\",\"siterank\":\"B01\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"中国人体艺术\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.rt114.org\",\"sitelink\":\"http://www.rt114.org/zg/index.html\",\"liststart\":\"<divclass=\\\"main\\\">\",\"listend\":\"<div>\",\"imagestart\":\"<divclass=\\\"picbox\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http://www.rt114.org/html\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"page\\\">\",\"pageend\"=\"...\",\"pagenext\"=\"page_(*)\"},");
        //21. 人体艺术
        result.Append("{\"siteid\":\"21\",\"siterank\":\"B02\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"人体艺术\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.rentiyishu88.org/rentiwaipai/\",\"sitelink\":\"http://www.rentiyishu88.org/rentiwaipai/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\"=\"</ul>\",\"pagenext\"=\"page_(*)\"},");
        //13. 妹子图
        result.Append("{\"siteid\":\"13\",\"siterank\":\"B03\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"妹子图【超快】\",\"listpage\":\"(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.mzitu.com\",\"sitelink\":\"http://www.mzitu.com/page/1\",\"liststart\":\"<divclass=\\\"postlist\",\"listend\":\"</ul>\",\"imagestart\":\"<divclass=\\\"main-image\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pagenavi\",\"pageend\"=\"</div>\",\"pagenext\"=\"/(*)\"},");
        //14. 猫扑炫图
        result.Append("{\"siteid\":\"14\",\"siterank\":\"B04\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"猫扑炫图\",\"listpage\":\"list_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://tt.mop.com\",\"sitelink\":\"http://tt.mop.com/xuan/list_1.html\",\"liststart\":\"<divclass=\\\"main\",\"listend\":\"<divclass=\\\"page\",\"imagestart\":\"<divclass=\\\"txtmod\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http://tt\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //15. ZOL人像摄影
        result.Append("{\"siteid\":\"15\",\"siterank\":\"B05\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"ZOL人像摄影\",\"listpage\":\"d16_pic_new_p(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://bbs.zol.com.cn\",\"sitelink\":\"http://bbs.zol.com.cn/dcbbs/d16_pic_new_p1.html\",\"liststart\":\"id=\\\"picBookList\\\"\",\"listend\":\"</ul>\",\"imagestart\":\"<divid=\\\"bookContent\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/dcbbs\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //10. 1000人体
        result.Append("{\"siteid\":\"10\",\"siterank\":\"B06\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"1000人体\",\"listpage\":\"index(*).htm\",\"pageencode\":\"gbk\",\"domain\":\"http://www.1000rtrt.com\",\"sitelink\":\"http://www.1000rtrt.com/yzrt/index.htm\",\"liststart\":\"<body\",\"listend\":\"</center>\",\"imagestart\":\"<p\",\"imageend\":\"<table\",\"oninclude\":\"/News\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //11. 人体艺术
        result.Append("{\"siteid\":\"11\",\"siterank\":\"\",\"viplevel\":\"2\",\"ishided\":\"1\",\"sitename\":\"人体艺术【失效】\",\"listpage\":\"list_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.68s.net\",\"sitelink\":\"http://www.68s.net/list/zhongguorenti/list_1.html\",\"liststart\":\"<divclass=\\\"list\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"imagestart\":\"<divclass=\\\"imgbox\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"http\",\"notinclude\":\"\",\"pagestart\":\"<divclass=\\\"pages\\\">\",\"pageend\"=\"</div>\",\"pagenext\"=\"\"},");
        //18. 黑丝网
        result.Append("{\"siteid\":\"18\",\"siterank\":\"\",\"viplevel\":\"3\",\"ishided\":\"1\",\"sitename\":\"黑丝网【失效】\",\"listpage\":\"index_(*).html\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.heisiwang.com\",\"sitelink\":\"http://www.heisiwang.com/xinggan/index.html\",\"liststart\":\"<divclass=\\\"channel-ctn\\\">\",\"listend\":\"<divclass=\\\"pages\\\">\",\"imagestart\":\"<divclass=\\\"endtext\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"/pic\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //19. 爱人体
        result.Append("{\"siteid\":\"19\",\"siterank\":\"B07\",\"viplevel\":\"2\",\"ishided\":\"0\",\"sitename\":\"爱人体\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.airenti.biz/yazhourenti/\",\"sitelink\":\"http://www.airenti.biz/yazhourenti/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<ulclass=\\\"file\\\">\",\"imageend\":\"</ul>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"photo\",\"pageend\"=\"</ul>\",\"pagenext\"=\"page_(*)\"},");
        //20. 漂漂美术馆
        result.Append("{\"siteid\":\"20\",\"siterank\":\"B08\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"漂漂美术馆\",\"listpage\":\"(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.ppmsg.net/jiepaimeinv/\",\"sitelink\":\"http://www.ppmsg.net/jiepaimeinv/index.html\",\"liststart\":\"<divclass=\\\"lm\\\">\",\"listend\":\"<ulclass=\\\"page\\\"\",\"imagestart\":\"<divid=\\\"imagelist\\\">\",\"imageend\":\"</div>\",\"oninclude\":\"20\",\"notinclude\":\"\",\"pagestart\":\"<ulclass=\\\"image\\\">\",\"pageend\"=\"</ul>\",\"pagenext\"=\"page_(*)\"},");
        //34. 福利图片
        result.Append("{\"siteid\":\"34\",\"siterank\":\"B09\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"福利图片【超快】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/福利图片/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //35. 街拍美女
        result.Append("{\"siteid\":\"35\",\"siterank\":\"B10\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"街拍美女【超快】\",\"listpage\":\"page/(*)\",\"pageencode\":\"utf-8\",\"domain\":\"http://www.dongde.in\",\"sitelink\":\"http://www.dongde.in/category/街拍美女/\",\"liststart\":\"<divclass=\\\"content\\\">\",\"listend\":\"<divclass=\\\"pagination\\\">\",\"imagestart\":\"<articleclass=\\\"article-content\\\">\",\"imageend\":\"</article>\",\"oninclude\":\"http://dongde.in/post\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"},");
        //36. 爱色阁-街拍图区
        result.Append("{\"siteid\":\"36\",\"siterank\":\"B11\",\"viplevel\":\"3\",\"ishided\":\"0\",\"sitename\":\"爱色阁-街拍图区【失效】\",\"listpage\":\"index44_(*).html\",\"pageencode\":\"gbk\",\"domain\":\"http://www.964vv.com\",\"sitelink\":\"http://www.964vv.com/html/part/index44.html\",\"liststart\":\"<divclass=list>\",\"listend\":\"<divclass=box_page>\",\"imagestart\":\"<divclass=content>\",\"imageend\":\"</div>\",\"oninclude\":\"/html/se\",\"notinclude\":\"\",\"pagestart\":\"\",\"pageend\"=\"\",\"pagenext\"=\"\"}");
        //end
        result.Append("],");

        //外部词典
		result.Append("\"ext_dic\":[\"内射\",\"內射\",\"车震\",\"大屁股\",\"人妻\",\"美臀\",\"肥臀\",\"翘臀\",\"换妻\",\"后入\",\"後入\",\"豐滿\",\"水多\",\"炮友\",\"網友\",\"白漿\",\"闺蜜\",\"陰道\",\"少婦\",\"熟婦\",\"賓館\",\"鮑魚\",\"極品\",\"鄰居\"],");

        //停止词典
		result.Append("\"stop_dic\":[\"的\",\"了\",\"在\",\"是\",\"我\",\"有\",\"和\",\"就\",\"不\",\"人\",\"都\",\"一\",\"一个\",\"上\",\"也\",\"很\",\"到\",\"说\",\"要\",\"去\",\"你\",\"会\",\"着\",\"没有\",\"看\",\"好\",\"自己\",\"这\"]}");

        Response.Write(result.ToString());
        Response.End();
    }
}